# Código Clase 6


## Numpy

In [ ]:
# Instalacion
!pip install numpy

In [ ]:
##para saber que version estoy usando

import numpy as np
print(np.__version__)  # o print(np.version.version)

Documentacion https://numpy.org/doc/2.2/user/absolute_beginners.html 

In [ ]:
# siempre antes de usar cualquier libreria tengo que importarla
# despues de importarla aclaro como la voy a llamar cuando la use, en este caso "np"
#import numpy as np

# Creacion de arrays

¿Que es un array o arreglo? Es una estructura de datos que almacena múltiples elementos en una sola variable. Todos los elementos suelen ser del mismo tipo y se organizan en posiciones indexadas(desde 0), lo que permite acceder a cada elemento mediante su índice.

A su vez pueden ser de 1, 2, 3 o N dimensiones :
* 1D → una lista

* 2D → una tabla

* 3D → un cubo

* nD → estructuras más complejas (por ejemplo, imágenes RGB o datos multivariantes en deep learning)

In [ ]:
# de 1 D 
# Son similares a listas en Python y representan una fila o columna de valores.
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

In [ ]:
print(arr1.ndim)  

In [ ]:
type(arr1)  

In [ ]:
# Secuencias
range_array = np.arange(0, 10, 2)              # Array de 0 a 10 de 2 en 2 // np.arange(start, stop, step)
linspace = np.linspace(0, 1, 5)                # 5 números equidistantes entre 0 y 1  // np.linspace(start, stop, num) util para dividir un intervalo en partes iguales
logspace = np.logspace(0, 2, 5)                # 5 números en escala logarítmica entre 10⁰ y 10²  //np.logspace(start_exp, stop_exp, num)  /graficos logaritmicos


In [ ]:
print(range_array)

In [ ]:
print(linspace)

In [ ]:
print(logspace)

In [21]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])  # Array 2D
print(arr2)


[[1 2 3]
 [4 5 6]]


In [ ]:
arr2.ndim  # Verifica la cantidad de dimensiones del array

2


In [23]:
arr2.shape  # Dimensiones del array (filas, columnas) // .shape devuelve una tupla con las dimensiones del array

(2, 3)

In [24]:
arr2.size

6

In [25]:
arr3 = np.array([
    # Primera capa
    [[1, 2, 3],  
     [7, 8, 9]],
    
    # Segunda capa
    [[10, 11, 12],  
     [16, 17, 18]]
])
print(arr3)

[[[ 1  2  3]
  [ 7  8  9]]

 [[10 11 12]
  [16 17 18]]]


In [27]:
arr3.ndim

3

In [ ]:
arr3.shape   ## devuelve una tupla con las dimensiones del array (profundidad, filas, columnas)

(2, 2, 3)

In [ ]:
# Funciones de creación
zeros = np.zeros((3, 4))       # Array 3x4 de ceros (filas, columnas)
ones = np.ones((2, 3, 4))      # Array 3D de unos (capas, filas, columnas)



In [ ]:
print(zeros) #print(ones) #print(empty) #print(identity) #print(diag)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
print(ones)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [33]:
# Arrays aleatorios
random_uniform = np.random.rand(2, 3)          # Distribución uniforme [0,1)
random_normal = np.random.randn(2, 3)          # Distribución normal (media=0, var=1)
random_int = np.random.randint(0, 10, (3, 3))  # Enteros aleatorios entre [0,10)

In [37]:
random_uniform

array([[0.99831945, 0.64464629, 0.74993812],
       [0.70650399, 0.59827655, 0.74866134]])

In [38]:
random_normal

array([[-1.32109539e-03, -2.56638440e+00, -4.89265158e-01],
       [ 1.37434718e-01,  2.05881294e+00, -8.50059503e-01]])

In [36]:
print(random_int)

[[7 0 1]
 [6 7 9]
 [6 3 0]]


# Propiedades de los arrays

In [39]:
# Consideremos este array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Propiedades básicas
print(arr.shape)    # Dimensiones: (2, 3)
print(arr.ndim)     # Número de dimensiones: 2
print(arr.size)     # Número total de elementos: 6
print(arr.dtype)    # Tipo de datos: int64


(2, 3)
2
6
int64


In [43]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Cambio de forma
reshaped = arr.reshape(3, 2)     # Cambia a 3x2 cambia la formma pero no el contenido
flattened = arr.flatten()        # Aplana a 1D: [1, 2, 3, 4, 5, 6]
transposed = arr.T               # Transpuesta: [[1, 4], [2, 5], [3, 6]] #La transpuesta de una matriz es una nueva matriz que se obtiene intercambiando filas por columnas.

In [42]:
reshaped

array([[1, 2],
       [3, 4],
       [5, 6]])

In [44]:
flattened

array([1, 2, 3, 4, 5, 6])

In [45]:
print(transposed)

[[1 4]
 [2 5]
 [3 6]]


# Indexing y slicing
Acceso básico

In [55]:
arr1

array([1, 2, 3, 4, 5])

In [58]:
print(arr1[3])

4


In [49]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]) 

In [50]:
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [53]:
arr.ndim
arr.shape

(3, 4)

In [50]:
# Acceso individual (filas, columnas)
print(arr[0, 0])    # 1 (primera fila, primera columna)
print(arr[2, 3])    # 12 (tercera fila, cuarta columna)


1
12


In [63]:
# Filas completas
print(arr[1])       # [5, 6, 7, 8] (segunda fila)

[5 6 7 8]


In [54]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [52]:
# Slicing [inicio:fin:paso]
print(arr[0:2, 1:3])  # [[2, 3], [6, 7]] (primeras 2 filas, columnas 1 y 2)
print(arr[:, 1])      # [2, 6, 10] (todas las filas, segunda columna)
print(arr[::2, ::2])  # [[1, 3], [9, 11]] (filas y columnas alternadas)

[[2 3]
 [6 7]]
[ 2  6 10]
[[ 1  3]
 [ 9 11]]


Indexacion avanzada

In [58]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
print(arr)

[10 20 30 40 50 60 70 80 90]


In [54]:
# Con listas de índices
indices = [1, 2, 6]
print(arr[indices])  # [20, 30, 70]


[20 30 70]


In [55]:
# Con arrays booleanos
mask = arr > 50
print(arr[mask])     # [60, 70, 80, 90]

[60 70 80 90]


In [56]:
# Combinación de condiciones
print(arr[(arr > 30) & (arr < 80)])  # [40, 50, 60, 70]


[40 50 60 70]


# Operaciones Vectorizadas
Operaciones Aritméticas

In [59]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [60]:
# Operaciones elemento a elemento
print(a + b)      # [6, 8, 10, 12]
print(a - b)      # [-4, -4, -4, -4]
print(a * b)      # [5, 12, 21, 32]
print(a / b)      # [0.2, 0.33, 0.43, 0.5]
print(a ** 2)     # [1, 4, 9, 16]
print(np.sqrt(a)) # [1., 1.41, 1.73, 2.]

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[ 1  4  9 16]
[1.         1.41421356 1.73205081 2.        ]


In [61]:
# Broadcasting (operaciones con escalares)
print(a + 10)     # [11, 12, 13, 14]
print(a * 2)      # [2, 4, 6, 8]

[11 12 13 14]
[2 4 6 8]


Funciones matemáticas comunes en NumPy

In [62]:
x = np.array([-2, -1, 0, 1, 2])


In [ ]:
# Funciones matemáticas
print(np.abs(x))            # [2, 1, 0, 1, 2] Valor absoluto
print(np.exp(x))            # [0.14, 0.37, 1., 2.72, 7.39]  Exponencial  //Útil en modelos de crecimiento, probabilidades, redes neuronales...
print(np.log([1, np.e, 10]))  # [0., 1., 2.3]
print(np.sin(x))            # [-.91, -.84, 0., .84, .91]


[2 1 0 1 2]
[0.13533528 0.36787944 1.         2.71828183 7.3890561 ]
[0.         1.         2.30258509]
[-0.90929743 -0.84147098  0.          0.84147098  0.90929743]


In [ ]:
# Redondeo
print(np.ceil([1.1, 2.5, 3.9]))   # [2., 3., 4.] redondeo hacia arriba
print(np.floor([1.1, 2.5, 3.9]))  # [1., 2., 3.] Redondeo hacia abajo
print(np.round([1.1, 2.5, 3.9]))  # [1., 2., 4.] Redondeo estándar

[2. 3. 4.]
[1. 2. 3.]
[1. 2. 4.]


**Ejercicio 1**: Responder las siguientes preguntas:
* ¿Qué operaciones se pueden hacer tanto en un arreglo de Numpy como en una lista? Dar un ejemplo en una celda.
* ¿Qué operaciones se pueden hacer en un arreglo de Numpy pero NO en una lista? Explorar algunas opciones y dar un ejemplo en una celda.
* ¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)? Pueden crear arreglos para intentar responder esa pregunta.

A partir de una lista podemos crear un arreglo de numpy

In [67]:
lista = [0,1,2,3,4,5]
arreglo = np.array(lista)
print(lista)
print(arreglo)

[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


Algunas cosas que se pueden hacer con arreglos pero no con las listas:

1. Sumarle un mismo elemento

In [3]:
lista + 1

TypeError: can only concatenate list (not "int") to list

In [4]:
arreglo = arreglo + 1

In [5]:
arreglo

array([1, 2, 3, 4, 5, 6])

2. Elevar al cuadrado todos los elementos

In [8]:
lista**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [9]:
arreglo**2

array([ 1,  4,  9, 16, 25, 36, 49, 64], dtype=int32)

3. Sumar todos los elementos

In [10]:
print(arreglo.sum())
print(lista.sum())

36


AttributeError: 'list' object has no attribute 'sum'

In [11]:
n = 0
for e in lista:
    n = n + e
print(n)

15


In [28]:
arreglo = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]] . Shape = (3, 6) 



In [30]:
arreglo = np.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1 2 3 4 5 6]] . Shape = (1, 6) 



In [31]:
arreglo = np.array([[1,2,3,4,5,6]]).T #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1) 



In [70]:
#¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)?

print('Arreglo de (n,)')
arreglo = np.array([1,2,3,4,5,6])
print(arreglo,'. Shape =', arreglo.shape, "\n") # "\n" imprime un salto de linea

print('Arreglo de (2,n)')
arreglo = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

print('Arreglo de (n,1)')
arreglo = np.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo.T,'. Shape =', arreglo.T.shape, "\n")   #notar .T, que significa transpuesto


Arreglo de (n,)
[1 2 3 4 5 6] . Shape = (6,) 

Arreglo de (2,n)
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]] . Shape = (2, 6) 

Arreglo de (n,1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1) 



In [ ]:
### EXTRA 1###
#Trasponer no es la unica forma de crear un arreglo de forma (n,1)'''
arreglo = np.array([[1],[2],[3],[4],[5],[6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape)   #notar .T, que significa transpuesto

In [43]:
a1 = np.array([[1,2,3,4],[5,6,7,8]])
a1.shape

(2, 4)

In [44]:
a2 = np.array([[1,2,3,4],[5,6,7,8]])
a2.shape

(2, 4)

In [45]:
a3 = a1 * a2
a3.shape

(2, 4)

In [46]:
a3

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

**Ejercicio 2**:
* Escribir un arreglo con números enteros del 0 al 9. Pista: arange
* Escribir un arreglo con 100 números equiespaciados del 0 al 9. Pista: linspace

In [ ]:
arreglo_1 = np.arange(0,10)
print(arreglo_1)

In [ ]:
arreglo_2 = np.linspace(0,9, 100)
print(arreglo_2)
print(len(arreglo_2))

**Ejercicio 3**:
* Escribir un arreglo con números enteros del 10 al 100 y seleccionar aquellos que son divisibles por 3<br>
Pista: mask

In [ ]:
a = np.arange(10,101)
a

In [ ]:
a = a.reshape(3,3,10)

In [ ]:
mask = (a%3==0) & (a > 90) #Creamos la máscara (filtro)
mask1 = a > 90

**Ejercicio 4**:
* Crear un arreglo de ceros de `shape` (5,10).
* Reemplazar la segunda y cuarta fila con unos
* Reemplazar la tercera y octava columna con dos (2).

In [ ]:
zeros = np.zeros((5,10), dtype = int)
zeros

In [ ]:
zeros[[1,3],:] = 1
zeros

In [ ]:
zeros[:,[2,7]] = 2
zeros

**Paginas para hacer ejercicios**:
Hacer todos los ejercicios que puedan del siguiente link https://www.machinelearningplus.com/python/101-numpy-exercises-python/

O de https://github.com/rougier/numpy-100

Para explorar las funciones de creación de datos aleatorios:
https://numpy.org/doc/stable/reference/random/legacy.html

In [17]:
a = np.random.random((4,2,3)) * 100 + 100
a

array([[[137.12277219, 187.22289567, 153.95764007],
        [175.21869487, 188.10311988, 118.02508687]],

       [[157.58773537, 166.74585121, 134.96866874],
        [128.3807111 , 188.91447629, 150.68622952]],

       [[168.77296873, 117.90287547, 115.19825164],
        [123.86197814, 172.33144425, 165.7329653 ]],

       [[157.35784374, 121.82035838, 100.01848734],
        [195.39977874, 188.95736542, 121.54200787]]])

In [18]:
a = np.random.random((4,4))

In [19]:
a

array([[0.48673571, 0.50465005, 0.33227167, 0.86611167],
       [0.14502147, 0.13692842, 0.56804006, 0.89177045],
       [0.78692331, 0.25942502, 0.88516122, 0.32876297],
       [0.78919257, 0.64347772, 0.02402004, 0.66363368]])

In [20]:
a = np.array([[10,200,30,45,5,50],[5,20,30,40,50,0],[5,20,30,40,50,0],[5,20,30,40,50,0]], dtype=np.int8)

In [115]:
a

array([[ 10, 200,  30,  45,   5, 100],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0]], dtype=int16)

In [21]:
a.sum()

519

In [22]:
a.std()

23.924904214367643

In [23]:
a.sort(axis=1)

In [24]:
a

array([[-56,   5,  10,  30,  45,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50]], dtype=int8)

In [25]:
a.sort(axis=0)
a

array([[-56,   5,  10,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  45,  50]], dtype=int8)

In [26]:
a[1:3,0:3]

array([[ 0,  5, 20],
       [ 0,  5, 20]], dtype=int8)

In [27]:
l =   [[ 10, 200,  30,  45,   5, 100],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0]]

In [28]:
a = np.array([l])

In [31]:
a.shape

(1, 4, 6)

In [32]:
a.reshape(24)

array([ 10, 200,  30,  45,   5, 100,   5,  20,  30,  40,  50,   0,   5,
        20,  30,  40,  50,   0,   5,  20,  30,  40,  50,   0])

In [33]:
a = np.matrix([[1,2,3,4,5,6]]) 
print(a) 

[[1 2 3 4 5 6]]


In [34]:
b = np.matrix([[1],[2],[3],[4],[5],[6]]) 
print(b) 

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [35]:
c = a * b 
print(c) 

[[91]]


In [36]:
d = b * a 
print(d)

[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]
 [ 6 12 18 24 30 36]]
